### ISSUE TITLE
Overlapping reference in <app>

### ISSUE THREAD

**Issue by matteodifranco** [evt-project/evt-viewer-angular#264]
In some cases, an `<app>` refers to multiple words, the last of which has an independent `<app>` that, however, is not displayed and lacks a reference, as in the following example:

```
<w xml:id="Cyzicus-03-1">ἔγωγ᾽</w>  
<w xml:id="Cyzicus-03-2">οὖν</w>  

```
[...]
```
<app from="#Cyzicus-03-1" to="#Cyzicus-03-2">
    <rdg resp="#Wilamowitz" wit="#Keil" type="editorial">ἐγὼ γοῦν</rdg>
</app>

<app from="#Cyzicus-03-2">
    <rdg wit="#F"><gap reason="lost"/></rdg>
</app>

```
In this example, the second `<app>` (gap in manuscript F) is not displayed.

<img width="791" alt="Image" src="https://github.com/user-attachments/assets/43f893b8-4c99-48ed-8e58-5f43119de7e8" />

**Comment by RenatoCaenaro** [comment]
Fixed in:
https://github.com/SilentWave/evt-viewer-angular/pull/16

try it on:
https://evt3-depa.silentwave.eu/

**Comment by matteodifranco** [comment]
Actually I still can't see the second <app> in 

```
<app from="#Cyzicus-03-1" to="#Cyzicus-03-2">
    <rdg resp="#Wilamowitz" wit="#Keil" type="editorial">ἐγὼ γοῦν</rdg>
</app>

<app from="#Cyzicus-03-2">
    <rdg wit="#F"><gap reason="lost"/></rdg>
</app>

```

on evt3-depa.silentwave.eu I see this:

<img width="849" alt="Image" src="https://github.com/user-attachments/assets/d977ea78-dec8-46d1-92f6-8db74f44bdca" />

and the xml is as follows:

```
<app from="#Cyzicus-03-1" to="Cyzicus-03-2">
<rdg resp="#Wilamowitz" wit="#Keil" type="editorial">ἐγὼ γοῦν</rdg>
</app>
<app from="#Cyzicus-03-2">
<!--
 ◊ questa #3-2 non compare perché
        #3-2 è anche sopra: come fare?
-->
<rdg wit="#F">
<gap reason="lost"/>
</rdg>
</app>
```

**Comment by RenatoCaenaro** [comment]
my fault, i updated the worng version in the server, try again:
https://evt3-depa.silentwave.eu/
to see this result:

![Image](https://github.com/user-attachments/assets/6db300d0-20fd-45f1-b348-b108c050bfaa)

**Comment by RenatoCaenaro** [comment]
@matteodifranco any feedback?

**Comment by matteodifranco** [comment]
> [@matteodifranco](https://github.com/matteodifranco) any feedback?

Thank you. The overlapping cases are sorted out. The two superscripts apexes are placed next to each other, but in reverse alphabetical order (in the example “clck”): is it possible to keep the alphabetical order in these cases?

**Comment by RenatoCaenaro** [comment]
@matteodifranco try now the order

**Comment by matteodifranco** [comment]
<img width="734" alt="Image" src="https://github.com/user-attachments/assets/81fe44f4-25ae-491b-97f8-55c6f7c1cf1a" />

The order is still reverse (brower's cache deleted before displaing)

**Comment by RenatoCaenaro** [comment]
![Image](https://github.com/user-attachments/assets/f3dd1e70-30fb-4bb5-9b95-42d5efca03fe)

you mean this order right?

**Comment by matteodifranco** [comment]
Yes, ba --> ab or (it would be much better) a-b
